spring:
  application:
    name: discovery-service
  profiles:
    active: @spring.active.profile@
  security:
    user:
      name: ${AUTH_USERNAME}
      password: ${AUTH_PASSWORD}

server:
  port: 8761

eureka:
  instance:
    hostname: ${DISCOVERY_HOST}
  client:
    service-url:
      defaultZone: https://${DISCOVERY_HOST}:${server.port}/eureka/

logging:
  level:
    org.springframework.security: INFO
    com.netflix.discovery: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health, info"
  endpoint:
    health:
      show-details: always
      show-components: always